// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkRlCbefTt7gcKQONEJuq6T81V1iYRZs',
    appId: '1:716641920547:web:39927d9937bdf290657396',
    messagingSenderId: '716641920547',
    projectId: 'flutter-vertex-ai-794b5',
    authDomain: 'flutter-vertex-ai-794b5.firebaseapp.com',
    storageBucket: 'flutter-vertex-ai-794b5.firebasestorage.app',
    measurementId: 'G-1T5T86TMX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ck_QLIYXBdzFe6yRNo52kC04OAvAoDQ',
    appId: '1:716641920547:android:d1ca56bf4e653d45657396',
    messagingSenderId: '716641920547',
    projectId: 'flutter-vertex-ai-794b5',
    storageBucket: 'flutter-vertex-ai-794b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrNoViJwiD8SM_h60KiOx9Qf3168QEJw',
    appId: '1:716641920547:ios:2d2de5a82d0b7bb1657396',
    messagingSenderId: '716641920547',
    projectId: 'flutter-vertex-ai-794b5',
    storageBucket: 'flutter-vertex-ai-794b5.firebasestorage.app',
    iosBundleId: 'com.gupta.flutterVertexAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVrNoViJwiD8SM_h60KiOx9Qf3168QEJw',
    appId: '1:716641920547:ios:2d2de5a82d0b7bb1657396',
    messagingSenderId: '716641920547',
    projectId: 'flutter-vertex-ai-794b5',
    storageBucket: 'flutter-vertex-ai-794b5.firebasestorage.app',
    iosBundleId: 'com.gupta.flutterVertexAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBkRlCbefTt7gcKQONEJuq6T81V1iYRZs',
    appId: '1:716641920547:web:06af2d7995db1101657396',
    messagingSenderId: '716641920547',
    projectId: 'flutter-vertex-ai-794b5',
    authDomain: 'flutter-vertex-ai-794b5.firebaseapp.com',
    storageBucket: 'flutter-vertex-ai-794b5.firebasestorage.app',
    measurementId: 'G-LS7MX5PGQ0',
  );
}
